Uppercase Docker Compose

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -2,6 +2,9 @@
 #set -euo pipefail
 set -uo pipefail
 
+__project_name="vouchdirk-docker"
+__app_name="Vouch"
+__sample_service="vouch"
 __docker_exe="docker"
 __compose_exe="docker compose"
 __compose_upgraded=0
@@ -37,9 +40,20 @@ determine_distro() {
 }
 
 determine_sudo() {
+    if [[ "$__distro" =~ "debian" || "$__distro" = "ubuntu" ]]; then
+        systemctl status docker >/dev/null
+        result=$?
+        if [ ! "${result}" -eq 0 ]; then
+            echo "The Docker daemon is not running. Please check Docker installation."
+            echo "\"sudo systemctl status docker\" and \"sudo journalctl -fu docker\" will be helpful."
+            echo "Aborting."
+            exit 1
+        fi
+    fi
+
     __maybe_sudo=""
     if ! docker images >/dev/null 2>&1; then
-        echo "Will use sudo to access docker"
+        echo "Will use sudo to access Docker"
         __maybe_sudo="sudo"
     fi
 }
@@ -62,13 +76,13 @@ determine_compose() {
     if [ -n "${ETHDSECUNDO-}" ]  || [ ! "${command}" = "update" ]; then # Don't run this twice
       echo
       echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc."
-      echo "Eth Docker will stop supporting it with Dencun, sometime fall 2023."
+      echo "${__project_name} will stop supporting it with Dencun, sometime early 2024."
       echo ""
-      echo "It is recommended that you replace compose V1 with compose V2."
+      echo "It is recommended that you replace Compose V1 with Compose V2."
       while true; do
-        read -rp "Do you want to update compose to V2? (yes/no) " yn
+        read -rp "Do you want to update Docker Compose to V2? (yes/no) " yn
         case $yn in
-          [Nn]* ) echo "Please be sure to update compose yourself!"; break;;
+          [Nn]* ) echo "Please be sure to update Docker Compose yourself!"; break;;
            * ) upgrade_compose; break;;
         esac
       done
@@ -82,15 +96,15 @@ determine_compose() {
 
 upgrade_compose() {
   if ! type -P docker-compose >/dev/null 2>&1; then
-    echo "Compose has already been updated to V2"
+    echo "Docker Compose has already been updated to V2"
     return
   fi
-  echo "Updating compose to V2"
+  echo "Updating Docker Compose to V2"
   if [[ "$__distro" = "ubuntu" ]]; then
     ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release
     __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
     if [ "${__major_version}" -lt 20 ]; then
-      echo "This script cannot update compose on Ubuntu ${__major_version}. Consider upgrading to 22.04 or 20.04"
+      echo "This script cannot update Docker Compose on Ubuntu ${__major_version}. Consider upgrading to 22.04 or 20.04"
       exit 0
     fi
     ${__auto_sudo} mkdir -p /etc/apt/keyrings
@@ -101,7 +115,7 @@ upgrade_compose() {
         https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
         | ${__auto_sudo} tee /etc/apt/sources.list.d/docker.list > /dev/null
     ${__auto_sudo} apt-get update
-    ${__auto_sudo} apt-get install -y docker-compose-plugin
+    ${__auto_sudo} apt-get install -y docker-compose-plugin docker-buildx-plugin
     echo "Installed docker-compose-plugin"
     __old_compose=0
     __compose_exe="docker compose"
@@ -117,7 +131,7 @@ upgrade_compose() {
     ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release
     __major_version=$(lsb_release -r | cut -f2)
     if [ "${__major_version}" -lt 10 ]; then
-        echo "This script cannot update compose on Debian ${__major_version}. Consider upgrading to 11 or 12."
+        echo "This script cannot update Docker Compose on Debian ${__major_version}. Consider upgrading to 11 or 12."
         exit 0
     fi
     ${__auto_sudo} mkdir -p /etc/apt/keyrings
@@ -128,7 +142,7 @@ upgrade_compose() {
         https://download.docker.com/linux/debian  $(lsb_release -cs) stable" \
         | ${__auto_sudo} tee /etc/apt/sources.list.d/docker.list > /dev/null
     ${__auto_sudo} apt-get update
-    ${__auto_sudo} apt-get install -y docker-compose-plugin
+    ${__auto_sudo} apt-get install -y docker-compose-plugin docker-buildx-plugin
     echo "Installed docker-compose-plugin"
     __old_compose=0
     __compose_exe="docker compose"
@@ -141,7 +155,7 @@ upgrade_compose() {
     ${__auto_sudo} apt-get remove -y docker-compose
     echo "Removed docker-compose"
   else
-    echo "This script does not know how to update compose on $__distro"
+    echo "This script does not know how to update Docker Compose on $__distro"
   fi
 }
 
@@ -158,13 +172,13 @@ handle_root() {
 check_for_snap() {
     if [[ "$__distro" = "ubuntu" && -n "$(which snap)" ]] && snap list 2>/dev/null | grep -qw 'docker'; then
         echo
-        echo "WARNING! Snap docker package detected. This WILL result in issues."
+        echo "WARNING! Snap Docker package detected. This WILL result in issues."
         echo "Removing the package will delete volumes and require a resync."
         echo
         echo "Doing so is still highly recommended however."
         echo
         echo "The exact steps depend a little on whether there already is"
-        echo "an apt version of docker installed as well, but in a nutshell"
+        echo "an apt version of Docker installed as well, but in a nutshell"
         echo '"./ethd stop" followed by "sudo snap remove --purge docker"'
         echo "and then a reboot, and as needed install docker.io or docker-ce with apt."
         echo
@@ -186,7 +200,7 @@ install() {
     check_for_snap
     set -e
     while true; do
-        read -rp "This will attempt to install docker and make your user part of the docker group. Do you wish to continue? (no/yes) " yn
+        read -rp "This will attempt to install Docker and make your user part of the docker group. Do you wish to continue? (no/yes) " yn
         case $yn in
             [Yy]* ) break;;
             * ) echo "Aborting, no changes made"; exit 0;;
@@ -195,11 +209,11 @@ install() {
     if [[ "$__distro" = "ubuntu" ]]; then
         __major_version=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'// | cut -d. -f1)
         if [ "${__major_version}" -lt 20 ]; then
-            echo "This script cannot install docker on Ubuntu ${__major_version}. Consider upgrading to 22.04."
+            echo "This script cannot install Docker on Ubuntu ${__major_version}. Consider upgrading to 22.04."
         fi
         if [ -z "$(which docker)" ]; then
             ${__auto_sudo} apt-get update && ${__auto_sudo} apt-get install -y ca-certificates curl gnupg lsb-release \
-                whiptail chrony
+                chrony pkg-config
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
             ${__auto_sudo} curl -fsSL https://download.docker.com/linux/ubuntu/gpg | ${__auto_sudo} gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             ${__auto_sudo} echo \
@@ -223,10 +237,10 @@ install() {
     elif [[ "$__distro" =~ "debian" ]]; then
         if [ -z "$(which docker)" ]; then
             ${__auto_sudo} apt-get update
-            ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release whiptail chrony
+            ${__auto_sudo} apt-get -y install ca-certificates curl gnupg lsb-release chrony pkg-config
             __major_version=$(lsb_release -r | cut -f2)
             if [ "${__major_version}" -lt 10 ]; then
-                echo "This script cannot install docker on Debian ${__major_version}. Consider upgrading to 12."
+                echo "This script cannot install Docker on Debian ${__major_version}. Consider upgrading to 12."
                 exit 0
             fi
             ${__auto_sudo} mkdir -p /etc/apt/keyrings
@@ -250,7 +264,7 @@ install() {
             echo "Your user is already part of the docker group"
         fi
     else
-        echo "This script does not know how to install docker on $__distro"
+        echo "This script does not know how to install Docker on $__distro"
     fi
     set +e
     return 0
@@ -512,7 +526,7 @@ printhelp() {
     echo ""
     echo "subcommands:"
     echo "  install"
-    echo "     attempts to install docker and docker-compose for you"
+    echo "     attempts to install Docker and Docker Compose for you"
     echo "  update"
     echo "     updates all client versions and vouchdirk-docker itself"
     echo "  up (or start)"
@@ -527,7 +541,7 @@ printhelp() {
     echo "  logs"
     echo "     shows logs"
     echo "  cmd <command>"
-    echo "     executes an arbitrary docker compose command. Use \"cmd help\" to list them"
+    echo "     executes an arbitrary Docker Compose command. Use \"cmd help\" to list them"
     echo "  terminate"
     echo "     stops the node and destroys all data stores"
     echo ""
@@ -538,7 +552,7 @@ printhelp() {
     echo "    shows logs only for dirk service"
     echo ""
     echo ""
-    echo "$me will attempt to use sudo as needed for docker commands"
+    echo "$me will attempt to use sudo as needed for Docker commands"
     echo ""
 }
 
@@ -569,16 +583,18 @@ command="$1"
 shift
 
 determine_distro
-determine_sudo
 handle_root
 prep_conffiles
-determine_docker
-determine_compose
 
+# Don't check for docker before it's installed
 if [ "$command" = "install" ]; then
     $command "$@"
     exit "$?"
 fi
+
+determine_sudo
+determine_docker
+determine_compose
 
 if ! dodocker images >/dev/null 2>&1; then
     echo "Please ensure you can call $__docker_exe before running this script."
@@ -601,7 +617,7 @@ check_disk_space
 
 if [ "${__compose_upgraded}" -eq 1 ]; then
   echo
-  echo "You updated compose to V2."
+  echo "You updated Docker Compose to V2."
   echo "The \"docker-compose\" command is gone and replaced with \"docker compose\"."
   echo "You can create yourself an alias for \"docker-compose\"."
   echo
@@ -610,9 +626,9 @@ if [ "${__compose_upgraded}" -eq 1 ]; then
 elif [ "${__old_compose}" -eq 1 ]; then
   echo
   echo "You are using docker-compose ${__compose_version}, which is unsupported by Docker, Inc. from July 2023 on."
-  echo "Eth Docker will stop supporting it with Dencun, sometime fall 2023."
+  echo "vouchdirk-docker will stop supporting it with Dencun, sometime early 2024."
   echo ""
   echo "A switch to docker-ce is recommended. It is *not* mandatory. This is unfortunately a manual step that "
-  echo "Eth Docker cannot do for you."
+  echo "vouchdirk-docker cannot do for you."
   echo "Please see https://ethdocker.com/Usage/Prerequisites#switching-from-dockerio-to-docker-ce for instructions."
 fi
